import { PrismaClient } from "@prisma/client";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

const prisma = new PrismaClient();

// Load client branding from seed-config.json (generated by setup.sh) with fallback defaults
interface SeedConfig {
  siteName?: string;
  siteDescription?: string;
  heroTitle?: string;
  heroSubtitle?: string;
  adminEmail?: string;
}

let seedConfig: SeedConfig = {};
const configPath = join(__dirname, "seed-config.json");
if (existsSync(configPath)) {
  try {
    seedConfig = JSON.parse(readFileSync(configPath, "utf-8"));
    console.log("Loaded branding from prisma/seed-config.json");
  } catch (e) {
    console.warn("Warning: Could not parse seed-config.json, using defaults");
  }
}

const defaultConfigs: Record<string, string> = {
  "site.name": seedConfig.siteName ?? "Community Site",
  "site.description": seedConfig.siteDescription ?? "A white-label community website with member registration and approval",
  "site.heroTitle": seedConfig.heroTitle ?? "Welcome to Our Community",
  "site.heroSubtitle": seedConfig.heroSubtitle ?? "Join our community today. Register and get approved to access member resources.",
  "site.theme": JSON.stringify({
    primary: "oklch(0.205 0 0)",
    primaryForeground: "oklch(0.985 0 0)",
    radius: "0.625rem",
  }),
  "registration.fields": JSON.stringify([
    {
      name: "fullName",
      label: "Full Legal Name",
      type: "text",
      required: true,
      placeholder: "Enter your full name",
    },
    {
      name: "address",
      label: "Street Address",
      type: "text",
      required: true,
      placeholder: "123 Main St",
    },
    {
      name: "city",
      label: "City",
      type: "text",
      required: true,
      placeholder: "City",
    },
    {
      name: "reason",
      label: "Why do you want to join?",
      type: "textarea",
      required: false,
      placeholder: "Tell us about yourself...",
    },
  ]),
  "email.adminNotifications": "true",
};

async function main() {
  console.log("Seeding database...");

  // Seed system membership tiers
  const systemTiers = [
    { id: "tier_pending", name: "Pending", slug: "pending", level: 0, isSystem: true, description: "Default tier for new users awaiting approval" },
    { id: "tier_member", name: "Member", slug: "member", level: 10, isSystem: false, description: "Standard member" },
    { id: "tier_admin", name: "Admin", slug: "admin", level: 999, isSystem: true, description: "Full system access" },
  ];

  for (const tier of systemTiers) {
    await prisma.membershipTier.upsert({
      where: { id: tier.id },
      update: {},
      create: tier,
    });
    console.log(`  Tier: ${tier.name} (level ${tier.level})`);
  }

  for (const [key, value] of Object.entries(defaultConfigs)) {
    await prisma.siteConfig.upsert({
      where: { key },
      update: {},
      create: { key, value },
    });
    console.log(`  Config: ${key}`);
  }

  await prisma.page.upsert({
    where: { slug: "about" },
    update: {},
    create: {
      slug: "about",
      title: "About Us",
      content: "Welcome to our community. This page can be edited by administrators.",
      published: true,
      sortOrder: 1,
    },
  });
  console.log("  Page: about");

  await prisma.page.upsert({
    where: { slug: "privacy" },
    update: {},
    create: {
      slug: "privacy",
      title: "Privacy Policy",
      content: "This privacy policy explains how we collect, use, and protect your personal information. This page can be edited by administrators.",
      published: true,
      sortOrder: 2,
    },
  });
  console.log("  Page: privacy");

  await prisma.page.upsert({
    where: { slug: "terms" },
    update: {},
    create: {
      slug: "terms",
      title: "Terms & Conditions",
      content: "These terms and conditions govern your use of this site and membership. This page can be edited by administrators.",
      published: true,
      sortOrder: 3,
    },
  });
  console.log("  Page: terms");

  console.log("Seed complete.");
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
